In [2]:
import xarray as xr
import schwabdev as sd
import json
import numpy as np
import pandas as pd
from datetime import datetime, date, timedelta, time
import calendar
import time as tm

from universes.universe_config import Universe_Config as uc

def create_client():
    """Create a Schwab client with API keys."""
    with open('keys.json', 'r') as f:
        keys = json.load(f)

    return sd.Client(keys['schwab']['app_key'], keys['schwab']['app_secret'])

client = create_client()

In [19]:
quotes_10 = []
for i in range(10):
    quotes_10.append(uc.return_universe_quotes("u01"))
    print(i)
    tm.sleep(60)

0
1
2
3
4
5
6
7
8
9

In [57]:
q0 = quotes_10[0]
q0 = q0.set_index(['ident'])
q0.columns

Index(['assetMainType', 'assetSubType', 'quoteType', 'realtime', 'ssid',
       'symbol', 'extended.askPrice', 'extended.askSize', 'extended.bidPrice',
       'extended.bidSize', 'extended.lastPrice', 'extended.lastSize',
       'extended.mark', 'extended.quoteTime', 'extended.totalVolume',
       'extended.tradeTime', 'fundamental.avg10DaysVolume',
       'fundamental.avg1YearVolume', 'fundamental.divAmount',
       'fundamental.divFreq', 'fundamental.divPayAmount',
       'fundamental.divYield', 'fundamental.eps',
       'fundamental.fundLeverageFactor', 'fundamental.lastEarningsDate',
       'fundamental.peRatio', 'quote.52WeekHigh', 'quote.52WeekLow',
       'quote.askMICId', 'quote.askPrice', 'quote.askSize', 'quote.askTime',
       'quote.bidMICId', 'quote.bidPrice', 'quote.bidSize', 'quote.bidTime',
       'quote.closePrice', 'quote.highPrice', 'quote.lastMICId',
       'quote.lastPrice', 'quote.lastSize', 'quote.lowPrice', 'quote.mark',
       'quote.markChange', 'quote.markPercentChange', 'quote.netChange',
       'quote.netPercentChange', 'quote.openPrice', 'quote.postMarketChange',
       'quote.postMarketPercentChange', 'quote.quoteTime',
       'quote.securityStatus', 'quote.totalVolume', 'quote.tradeTime',
       'reference.cusip', 'reference.description', 'reference.exchange',
       'reference.exchangeName', 'reference.isHardToBorrow',
       'reference.isShortable', 'reference.htbQuantity', 'reference.htbRate',
       'regular.regularMarketLastPrice', 'regular.regularMarketLastSize',
       'regular.regularMarketNetChange', 'regular.regularMarketPercentChange',
       'regular.regularMarketTradeTime', 'fundamental.declarationDate',
       'fundamental.divExDate', 'fundamental.divPayDate',
       'fundamental.nextDivExDate', 'fundamental.nextDivPayDate',
       'reference.otcMarketTier', 'reference.fsiCode', 'reference.fsiDesc',
       'invalidSymbols'],
      dtype='object')

In [58]:
q0['quote.quoteTime'] = pd.to_datetime(q0['quote.quoteTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.tradeTime'] = pd.to_datetime(q0['quote.tradeTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.askTime'] = pd.to_datetime(q0['quote.askTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.bidTime'] = pd.to_datetime(q0['quote.bidTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['regular.regularMarketTradeTime'] = pd.to_datetime(q0['regular.regularMarketTradeTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))

In [59]:
q0[['quote.totalVolume','quote.lastSize','quote.tradeTime','quote.askTime','quote.bidTime','quote.quoteTime']]

,quote.totalVolume,quote.lastSize,quote.tradeTime,quote.askTime,quote.bidTime,quote.quoteTime
ident,,,,,,
WBD,25303743.0,796.0,2025-07-30 13:11:59.479000-04:00,2025-07-30 13:11:59.481000-04:00,2025-07-30 13:11:59.481000-04:00,2025-07-30 13:11:59.481000-04:00
F,30492797.0,100.0,2025-07-30 13:11:58.979000-04:00,2025-07-30 13:11:51.108000-04:00,2025-07-30 13:11:58.254000-04:00,2025-07-30 13:11:58.254000-04:00
BBAI,28702471.0,200.0,2025-07-30 13:11:55.644000-04:00,2025-07-30 13:11:55.866000-04:00,2025-07-30 13:11:56.197000-04:00,2025-07-30 13:11:56.197000-04:00
PSLV,20398450.0,146.0,2025-07-30 13:11:52.759000-04:00,2025-07-30 13:11:55.085000-04:00,2025-07-30 13:11:53.056000-04:00,2025-07-30 13:11:55.085000-04:00
VALE,31018502.0,400.0,2025-07-30 13:11:59.356000-04:00,2025-07-30 13:11:56.278000-04:00,2025-07-30 13:11:56.278000-04:00,2025-07-30 13:11:56.278000-04:00
...,...,...,...,...,...,...
PBSFY,0.0,0.0,2025-07-18 13:20:50.197000-04:00,2025-07-30 12:08:29.873000-04:00,2025-07-30 11:32:11.605000-04:00,2025-07-30 12:08:29.873000-04:00
SMGBF,0.0,1000.0,2025-07-28 15:49:17.936000-04:00,2025-07-30 09:56:16.262000-04:00,2025-07-30 09:30:05.581000-04:00,2025-07-30 09:56:16.262000-04:00
SWRBF,0.0,100.0,2025-07-29 14:09:46.300000-04:00,2025-07-30 09:56:16.255000-04:00,2025-07-30 09:56:10.852000-04:00,2025-07-30 09:56:16.255000-04:00
CYGIY,0.0,20.0,2025-07-28 12:19:37.671000-04:00,2025-05-16 17:00:03.274000-04:00,2025-05-16 17:00:03.274000-04:00,2025-05-16 17:00:03.274000-04:00
SATLF,0.0,0.0,2025-07-22 09:30:17.434000-04:00,2025-07-30 07:20:34.956000-04:00,2025-07-30 07:03:05.847000-04:00,2025-07-30 07:20:34.956000-04:00

In [64]:
import matplotlib.pyplot as plt
q0[['quote.totalVolume','quote.lastSize','quote.tradeTime','quote.askTime','quote.securityStatus']][q0['quote.securityStatus'] != 'Normal'].sort_values(by='quote.tradeTime')

,quote.totalVolume,quote.lastSize,quote.tradeTime,quote.askTime,quote.securityStatus
ident,,,,,
errors,NaN,NaN,NaT,NaT,NaN
errors,NaN,NaN,NaT,NaT,NaN